services:
  - type: web
    name: recipe-app
    env: node
    branch: main
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
